### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [m1n0s/kottans-js-2016#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by m1n0s** [comment]
![image](https://cloud.githubusercontent.com/assets/12004923/15550183/ebd5530a-22b8-11e6-9396-8f01e1183bb2.png)

**Comment by m1n0s** [comment]
I've done my screenshot with UA l10n for you sure that I doesn't stole this from another student 😸
