### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [m1n0s/kottans-js-2016#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by m1n0s** [comment]
My goal is avoid `div` tags and create this markdown without `class` attr.

https://github.com/m1n0s/kottans-js-2016/blob/master/week01/habrahabr-244929.html

**Comment by mkozhukharenko** [comment]
##### dt dl - isn't appropriate use case

Why did you use dd and dl elements here?

> The dl element represents an association list consisting of zero or more name-value groups (a description list). A name-value group consists of one or more names (dt elements) followed by one or more values (dd elements), **ignoring any nodes other than dt and dd elements**.
> 
> The dt element represents the term
> The dd element represents the description

[source of truth](https://html.spec.whatwg.org/#the-dl-element)

``` html
<dl>
       <a href="#" role=button>
              <dt>Профиль</dt>
              <dd><img src="#" alt=man></dd>
       </a>
</dl>       
<dl>
   <dt>Пользователь</dt>
    <dd>@rayproud</dd>
</dl>
```

---

##### 2 use 'meter' for 'Карма'

---

##### use html validator

https://validator.w3.org/nu/
here is an error: http://image.prntscr.com/image/4901552e4bb644a78147135212bcd77d.png that I wrote about above 

##### don't use two 'main' elements

---

##### in footer 'Разделы' can also be a 'nav'

"Похожие публикации" should be 'aside'

**Comment by shvaikalesh** [comment]
first `<aside>`: I would rather replace `h1`s and remove `section`s

**Comment by shvaikalesh** [comment]
last `<footer>`: replace `<li>` with `section`

**Comment by shvaikalesh** [comment]
🏆 for hidden headers

**Comment by m1n0s** [comment]
@mkozhukharenko Thanks! Good noticing against my stupid mistakes 👍 
@shvaikalesh Thanks, especially for 🏆. 

> last `<footer>`: replace `<li>` with `section`

I was sure you said that in footer should be list of lists, but now I find that words on video and they are not exactly the same :grimacing:

**Comment by shvaikalesh** [comment]
yandex ads would be `article`s

https://github.com/m1n0s/kottans-js-2016/blob/master/week01/habrahabr-244929.html#L69

bloats outline too much. leave one single `section`

**Comment by m1n0s** [comment]
@shvaikalesh, I agree. Fixed ^^
