### ISSUE TITLE
Домашнее задание по тестированию

### ISSUE THREAD

**Issue by tiny-kottan** [m1n0s/kottans-js-2016#7]
https://github.com/timoxley/functional-javascript-workshop - complete 'Function Spies' exercise.
Investigate following questions:
  1) What are stubs, mocks? What is the difference?
  2) What is the difference between TDD and BDD?
Read about several test frameworks / setups, pick one (qunit, jasmine, mocha, ava, tape). 
Do Kata #1 using it.

**Comment by m1n0s** [comment]
https://github.com/m1n0s/kottans-js-2016/tree/master/hw6

The only one thing what I didn't handle is when delimiters includes template symbols (e.g. `*` or `?`). I decided that this is not important part of TDD kata idea.

![image](https://cloud.githubusercontent.com/assets/12004923/16607069/eaaa9e42-4345-11e6-8697-86dc90873e46.png)
